[package]
name = "rust_torrent"
version = "0.1.0"
authors = ["pj"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-serialize = "0.3"
bip_bencode = "0.4.4"

[[bin]]
name = "rust_torrent"
path = "main.rs"
